module.exports = [
  {
    name: "Amazin Store",
    email: "amazin@email.com",
    password: "password",
    isAdmin: true,
  },

  {
    name: "John Smith",
    email: "john@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Michael Johnson",
    email: "michael@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Samantha Lee",
    email: "samantha@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "David Kim",
    email: "david@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Sarah Park",
    email: "sarah@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Peter Chen",
    email: "peter@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Karen Wong",
    email: "karen@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "James Tan",
    email: "james@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Linda Zhang",
    email: "linda@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Emily Chen",
    email: "emily@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Michael Johnson",
    email: "michael1@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Sarah Davis",
    email: "sarah2@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "David Kim",
    email: "david3@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Karen Lee",
    email: "karen2@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Matthew Brown",
    email: "matthew22@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Jessica Taylor",
    email: "jessica2@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Brian Wilson",
    email: "brian2@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Samantha Anderson",
    email: "samantha3@email.com",
    password: "password",
    isAdmin: false,
  },
  {
    name: "Andrew Nguyen",
    email: "andrew3@email.com",
    password: "password",
    isAdmin: false,
  },
];
